import fertil from '../../fixtures/fertil.json'
describe('tactos', () => {
    beforeEach("ingresa", () => {
        cy.viewport(1536, 960)
        cy.visit("https://test.crecientefertil.com.ar/");
        cy.get('.mt-5').click()

        cy.get('#username').type(fertil.fertilname)
        cy.get('#password').type(fertil.fertilpas)
        cy.contains('Ingresar').click()
        cy.wait(4000)
        //cy.get('.scrollbar-thin > .overflow-y-auto > :nth-child(8) > .flex')
        cy.get('a').contains('Tactos').click()
        cy.wait(1000)
    })
    it("nuevo tacto", () => {
        cy.contains('+ Nuevo tacto').click()
        cy.wait(2000)
        cy.get("#fecha").click()
        cy.get('.absolute > :nth-child(3) > :nth-child(3)').click()
        cy.get('[name="observacion"]').eq(0).type(fertil.tactonuevo.observacion)
        cy.get('#tipotacto').select(0, { force: true })
        cy.get('tbody tr').first().find('label').click()
        cy.get('div.border-t.border-cf-border')
            .contains('button', 'Siguiente')
            .click()
        cy.get('.bg-cf-primary')
            .contains('button', 'Crear tacto')
            .click()
        cy.wait(1000)
        cy.get('.swal2-confirm').click()
        cy.wait(2000)
    })
    it("editar tacto", () => {
        cy.wait(5000)
        cy.intercept('*', { forceNetworkError: true }).as('offline')
        cy.get('tbody tr').first().within(() => {
            // Busca todos los botones en la última celda (acciones)
            cy.get('td:last-child button')
                .eq(1) // El índice 1 es el segundo botón = Pencil
                .click()
        })
        cy.wait(1000)
        cy.get('[name="observacion"]').eq(0).clear()
        cy.get('[name="observacion"]').eq(0).type(fertil.tactonuevo.observacionnuevo)
        cy.get('div.border-t.border-cf-border')
            .contains('button', 'Siguiente')
            .click()
        cy.get('.bg-cf-primary')
            .contains('button', 'Actualizar tacto')
            .click()
        cy.get('.swal2-confirm').click()

        cy.wait(1000)

    })
    it("eliminar tacto", () => {
        cy.wait(5000)
        cy.intercept('*', { forceNetworkError: true }).as('offline')
        cy.get('tbody tr').first().within(() => {
            // Busca todos los botones en la última celda (acciones)
            cy.get('td:last-child button')
                .eq(2)
                .click()
        })
        cy.wait(1000)
        cy.get('.swal2-confirm').click()
        cy.wait(1000)
        cy.get('.swal2-confirm').click()
        cy.wait(1000)
    })
    it("nuevo tacto", () => {
        cy.wait(5000)
        cy.intercept('*', { forceNetworkError: true }).as('offline')
        cy.contains('+ Nuevo tacto').click()
        cy.wait(2000)
        cy.get("#fecha").click()
        cy.get('.absolute > :nth-child(3) > :nth-child(3)').click()
        cy.get('[name="observacion"]').eq(0).type(fertil.tactonuevo.observacion)
        cy.get('#tipotacto').select(0, { force: true })
        cy.get('tbody tr').first().find('label').click()
        cy.get('div.border-t.border-cf-border')
            .contains('button', 'Siguiente')
            .click()
        cy.get('.bg-cf-primary')
            .contains('button', 'Crear tacto')
            .click()
        cy.wait(1000)
        cy.get('.swal2-confirm').click()
        cy.wait(2000)
    })
})